### ISSUE TITLE
Question about netopeer, starting daemons, and ofc-server error

### ISSUE THREAD

**Issue by snrism** [openvswitch/of-config#12]
Hi,
Newbie question..Any help is appreciated

I managed to get the ofc-server running, but wasn't sure on the following:
 QN1: netopeer installation requirements
 QN2: ofc-server connection to ofc-bridge
 QN3: required steps to start all needed daemons and clients:

QN1: Netopeer Installation:
 Do I have to install the netopeer/server as well or will netopeer-cli suffice? my initial understanding from README was, netopeer is only used for cli and it will talk to libnetconf (which will run the netconf server)? 
++ If yes, can you tell me the setup for libnetconf and how to start the netconf server and how to connect from netopeer-cli? 
++ If no, can you please clarify on the netopeer & netconf server setup?

QN2: I wasn't entirely sure on the correct order to start all daemons. Currently my ofc-server is running and is connected to OVSDB, but I get an error on the connection to ofc-bridge.  My ovs is installed correctly and I am able to see a default bridge named 'ofc-bridge' is added. Then, when I start ofc-server -v 3 -f , i get the following:

ofc-server[7089]: Shared memory key: -4
ofc-server[7089]: Shared memory ID: 163840
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-inet-types.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-yang-types.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-netconf-monitoring.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-netconf-notifications.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model nc-notifications.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model notifications.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-netconf-with-defaults.
ofc-server[7089]: Checking the default Events stream path //var/lib/libnetconf//streams/.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model ietf-x509-cert-to-name.
ofc-server[7089]: NACM turned off, module 'ietf-netconf-acm' is not available for import from 'ietf-netconf-server'.
ofc-server[7089]: ncds_new_internal: Relax NG validator set (/usr/local/var/ofconfig/ietf-netconf-server/ietf-netconf-server-config.rng)
ofc-server[7089]: ncds_new_internal: Schematron validator set (/usr/local/var/ofconfig/ietf-netconf-server/ietf-netconf-server-schematron.xsl)
ofc-server[7089]: Datastore ietf-netconf-server initiated with ID 1804289384.
ofc-server[7089]: ncds_features_parse: no feature definitions found in data model of-config.
ofc-server[7089]: ncds_new_internal: Relax NG validator set (/usr/local/var/ofconfig/of-config/of-config-config.rng)
ofc-server[7089]: ncds_new_internal: Schematron validator set (/usr/local/var/ofconfig/of-config/of-config-schematron.xsl)
ofc-server[7089]: Try to synchronize OVSDB.
2015-04-10T23:05:37Z|00001|reconnect|INFO|unix://var/run/openvswitch/db.sock: connecting...
2015-04-10T23:05:37Z|00002|reconnect|INFO|unix://var/run/openvswitch/db.sock: connected
ofc-server[7089]: OF-CONFIG datastore initialized.
ofc-server[7089]: Datastore of-config initiated with ID 846930887.
ofc-server[7089]: Setting default configuration for ietf-netconf-server module
ofc-server[7089]: callback_srv_netconf_srv_ssh_srv_listen_oneport: port 830
ofc-server[7089]: callback_srv_netconf_srv_ssh_srv_listen: started sshd (PID 7090)
ofc-server[7089]: OFC COPY-CONFIG (from <config> to running)
ofc-server[7089]: Deleting all OVSDB content
ofc-server[7089]: OVSDB transaction successful
ofc-server[7089]: OVSDB unchanged
Could not load host key: /etc/ssh/ssh_host_ed25519_key
ofc-server[7089]: OFC COPY-CONFIG (from startup to running)
ofc-server[7089]: Creating the node capable-switch
ofc-server[7089]: Creating the node id
ofc-server[7089]: Creating the node resources
ofc-server[7089]: Creating the node port
ofc-server[7089]: Creating the node logical-switches
ofc-server[7089]: Creating the node switch
ofc-server[7089]: OVSDB transaction successful
ofc-server[7089]: OpenFlow: connecting to unix://var/run/openvswitch/ofc-bridge.mgmt
ofc-server[7089]: OpenFlow: ofc-bridge: failed to connect to socket (Connection reset by peer).
ofc-server[7089]: OpenFlow: connecting to unix://var/run/openvswitch/ofc-bridge.mgmt
2015-04-10T23:05:38Z|00003|timeval|WARN|Unreasonably long 1001ms poll interval (0ms user, -1ms system)
ofc-server[7089]: ovs|00003|timeval|WARN|Unreasonably long 1001ms poll interval (0ms user, -1ms system)
2015-04-10T23:05:38Z|00004|timeval|WARN|faults: 12 minor, 0 major
ofc-server[7089]: ovs|00004|timeval|WARN|faults: 12 minor, 0 major
2015-04-10T23:05:38Z|00005|timeval|WARN|context switches: 1 voluntary, 1 involuntary
ofc-server[7089]: ovs|00005|timeval|WARN|context switches: 1 voluntary, 1 involuntary
2015-04-10T23:05:38Z|00006|coverage|INFO|Event coverage, avg rate over last: 5 seconds, last minute, last hour,  hash=27900043:
ofc-server[7089]: ovs|00006|coverage|INFO|Event coverage, avg rate over last: 5 seconds, last minute, last hour,  hash=27900043:
2015-04-10T23:05:38Z|00007|coverage|INFO|txn_unchanged              0.0/sec     0.000/sec        0.0000/sec   total: 1
ofc-server[7089]: ovs|00007|coverage|INFO|txn_unchanged              0.0/sec     0.000/sec        0.0000/sec   total: 1
2015-04-10T23:05:38Z|00008|coverage|INFO|txn_incomplete             0.0/sec     0.000/sec        0.0000/sec   total: 3
ofc-server[7089]: ovs|00008|coverage|INFO|txn_incomplete             0.0/sec     0.000/sec        0.0000/sec   total: 3
2015-04-10T23:05:38Z|00009|coverage|INFO|txn_success                0.0/sec     0.000/sec        0.0000/sec   total: 2
ofc-server[7089]: ovs|00009|coverage|INFO|txn_success                0.0/sec     0.000/sec        0.0000/sec   total: 2
2015-04-10T23:05:38Z|00010|coverage|INFO|poll_fd_wait               0.0/sec     0.000/sec        0.0000/sec   total: 16
ofc-server[7089]: ovs|00010|coverage|INFO|poll_fd_wait               0.0/sec     0.000/sec        0.0000/sec   total: 16
2015-04-10T23:05:38Z|00011|coverage|INFO|poll_zero_timeout          0.0/sec     0.000/sec        0.0000/sec   total: 2
ofc-server[7089]: ovs|00011|coverage|INFO|poll_zero_timeout          0.0/sec     0.000/sec        0.0000/sec   total: 2
2015-04-10T23:05:38Z|00012|coverage|INFO|util_xalloc                0.0/sec     0.000/sec        0.0000/sec   total: 4064
ofc-server[7089]: ovs|00012|coverage|INFO|util_xalloc                0.0/sec     0.000/sec        0.0000/sec   total: 4064
2015-04-10T23:05:38Z|00013|coverage|INFO|vconn_open                 0.0/sec     0.000/sec        0.0000/sec   total: 4
ofc-server[7089]: ovs|00013|coverage|INFO|vconn_open                 0.0/sec     0.000/sec        0.0000/sec   total: 4
2015-04-10T23:05:38Z|00014|coverage|INFO|vconn_sent                 0.0/sec     0.000/sec        0.0000/sec   total: 2
ofc-server[7089]: ovs|00014|coverage|INFO|vconn_sent                 0.0/sec     0.000/sec        0.0000/sec   total: 2
2015-04-10T23:05:38Z|00015|coverage|INFO|hmap_pathological          0.0/sec     0.000/sec        0.0000/sec   total: 21
ofc-server[7089]: ovs|00015|coverage|INFO|hmap_pathological          0.0/sec     0.000/sec        0.0000/sec   total: 21
2015-04-10T23:05:38Z|00016|coverage|INFO|hmap_expand                0.0/sec     0.000/sec        0.0000/sec   total: 94
ofc-server[7089]: ovs|00016|coverage|INFO|hmap_expand                0.0/sec     0.000/sec        0.0000/sec   total: 94
2015-04-10T23:05:38Z|00017|coverage|INFO|stream_open                0.0/sec     0.000/sec        0.0000/sec   total: 5
ofc-server[7089]: ovs|00017|coverage|INFO|stream_open                0.0/sec     0.000/sec        0.0000/sec   total: 5
2015-04-10T23:05:38Z|00018|coverage|INFO|47 events never hit
ofc-server[7089]: ovs|00018|coverage|INFO|47 events never hit
ofc-server[7089]: OpenFlow: ofc-bridge: successful connection.
ofc-server[7089]: Transapi calling callback /A:capable-switch with op ADD.
ofc-server[7089]: OF-CONFIG data affected.
ofc-server[7089]: OF-CONFIG server successfully initialized.

The log indicates that the ofc-server is connected to the ovsdb, but it is unable to talk to ofc-bridge. Any conf required in ovs to make ofc-bridge listen to of-config calls?

QN3: Steps to start all daemons and issue commands:
++  Run OVS (which starts ovsdb internall and configures ofc-bridge)
++  Run ofc-server with ofc-server -v 3 -f
++ Start netconf server via libnetconf?? Not sure.. Or start the netopeer/server??
++ Setup netopeer cli and connect to the netconf server
++ Write XML files (currently use the netconf-tests folder samples) to issue commands..

Is this correct?

Thanks,
Sriram

**Comment by cejkato2** [comment]
QN1: Netopeer Installation:
Netopeer is not required to run OF-CONFIG server. Netopeer-cli is just our recommendation of NETCONF client (and it is contained in netopeer repository). In addition, netopeer-cli is used in netconf-tests/ scripts

QN2:
"ofc-server[7089]: OpenFlow: ofc-bridge: successful connection." -> it seems correct, you can check it by running get-config etc. For explanation, see commit 7118110ad3d

QN3:
1) Run OVS (for me, it is /usr/share/openvswitch/scripts/ovs-ctl start)
2) Run ofc-server (as you suggested)
3) use any NETCONF client (e.g. netopeer-cli) to connect to ofc-server via 830/TCP (default NETCONF port)

There is no additional action required, you **shouldn't** run any netopeer-server.

**Comment by snrism** [comment]
@cejkato2 Works for me...thanks for the clarification. I can now connect to the ofc-server and able to run the sample scripts as well.

Thanks,
Sriram

**Comment by Sandhyasharad** [comment]
Hi,
I am able to build of-config successfully.
Now I got a basic question on of-config usage.
Is of-config support required on controller side?  as we can communicate with ofc-server using ssh with subsystem as netconf (ssh -p 830 root@192.168.122.22 -s netconf).
As per my understanding, ofc-server and ofc-agent both should run on Open Flow capable switch. And not required on controller. 
Please let me know whether my understanding is correct or am I missing anything.
Thanks,
Sandhya

**Comment by rkrejci** [comment]
Hi Sandhya,
OF-CONFIG support is required on "Configuration Point" side - see the [spec](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow-config/of-config-1.2.pdf) for difference between "Configuration Point" and "Controller". You are right that ofc-server and ofc-agent are both the server-side (switch) applications, for the configuration point you need an OF-CONFIG client-side application.

Note, that OF-CONFIG is actually NETCONF with specific YANG schema, so on the client-side, you need a NETCONF client supporting the OF-CONFIG 1.2 (with some modifications, data model is available [here](https://github.com/openvswitch/of-config/tree/master/model), in the source code repository) YANG schema.

**Comment by Sandhyasharad** [comment]
Hi Radek,
Thanks for quick response. 
We are using controller as configuration point. So here we have integrated the libnetconf  with our controller and sending the configuration. So as you mentioned we are assuming of-config support is not required at controller side.
Thanks,
Sandhya
