### ISSUE TITLE
Create Usage Instructions for New Users

### ISSUE THREAD

**Issue by snrism** [openvswitch/of-config#14]
For starters like me, I found the netconf-tests scripts to be very useful. However, I have previously worked on OpenFlow and hence it was easy for me to figure out which files to try out. 

A tutorial file with instruction to execute simple netconf scripts and the order in which they should be executed will help users big time, example like this https://github.com/openvswitch/ovs/blob/master/tutorial/Tutorial.md

I believe the README file here https://github.com/openvswitch/of-config/tree/master/netconf-tests has that information. But some additional explanation on the usage will help.

Thanks,
Sriram

**Comment by cejkato2** [comment]
@snrism I hope it should be better... Any comments or can we close this?

**Comment by snrism** [comment]
@cejkato2 Sorry, just saw this. Looks good for now. Thanks

**Comment by cejkato2** [comment]
Thank you for your feedback that helped to improve doc :-)
