### ISSUE TITLE
Create a Vagrant and Docker Setup

### ISSUE THREAD

**Issue by snrism** [openvswitch/of-config#15]
For easier user setup and access to OF-Config, I suggest setting up a vagrant build containing all requirements for OFC Server and its components running on it.

In addition, a docker container hosted in docker repo with ofc-server will make life easier for anyone trying to replicate ofc-server setup and directly go on to use the server to play with netconf

I am happy to work on a Dockerfile and Vagrantfile with usage instructions (if that helps)

Thanks,
Sriram

**Comment by rkrejci** [comment]
Our original idea was to have VM image for this purposes. It was already created and we are waiting for ONF to make it available on their site.

Anyway, I'm fine with you preparing the docker for ofc-server and even with vagrant. However, I believe that the main way (or the way with main focus of mine) how to use ofc-server should be the autotools way via the configure script.

**Comment by snrism** [comment]
Agreed on the autotools, but I believe the vagrant setup will help folks to try out the system in their dev environment. I will prepare one. Thanks

**Comment by cejkato2** [comment]
Merged, thanks for pull request.
I went through the files and it seems to be fine.
