### ISSUE TITLE
configure.ac - configure file issue

### ISSUE THREAD

**Issue by abhsob** [openvswitch/of-config#2]
I see the following issue when generating configure file. RHEL 6.5. Can these be ignored?

autoconf configure.ac > configure
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:21: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:25: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:27: error: possibly undefined macro: AC_DEFINE_DIR
configure.ac:29: error: possibly undefined macro: LT_INIT
configure.ac:51: error: possibly undefined macro: AM_CONDITION

The configure file is generated so I tried to execute it. On running the configure see the following issue related to AM_INIT_AUTOMAKE

/configure: line 1819: syntax error near unexpected token `foreign'
./configure: line 1819:`AM_INIT_AUTOMAKE(foreign subdir-objects)'

**Comment by blp** [comment]
That's not how you invoke autoconf.  Please use boot.sh.

**Comment by abhsob** [comment]
Thanks for the quick resolution.

I am running into another error:

configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath

I searched for the file in the system but don't find it. I checked the
instructions for installation of openvswitch and I see that I have built it
as per the instructions. I used to openvswitch tarball install. Do I need
to do anything differently?

Thanks,
Abhijeet

On Fri, Mar 13, 2015 at 3:59 PM, Ben Pfaff notifications@github.com wrote:

> That's not how you invoke autoconf. Please use boot.sh.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openvswitch/of-config/issues/2#issuecomment-79516868.

## 

abhijeet

**Comment by cejkato2** [comment]
Look at https://github.com/openvswitch/of-config/blob/master/INSTALL.md#open-vswitch-installation
You have to configure and make Open vSwitch. That is the place where OF-CONFIG's configure looks for all OVS stuff...
After successful build of OVS (make install is not necessary if you installed OVS in different way), configuration and build of OF-CONFIG can be done. https://github.com/openvswitch/of-config/blob/master/INSTALL.md#of-config-installation

**Comment by abhsob** [comment]
I already have openvswitch running:

 ovs-vsctl show
760fdf5b-6eed-45b2-8573-5626dd978df1
    Bridge "br0"
        Controller "tcp:x.x.x.x:6633" (modified to hide network IP)
        Port "tap1"
            Interface "tap1"
        Port "br0"
            Interface "br0"
                type: internal
        Port "tap0"
            Interface "tap0"
    ovs_version: "2.3.1"

Just to clarify, I did not build openvswitch from github sources but used
the tarball install. The
./configure --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

This is the output for
[root@abso98 of-config]# ./configure
--with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for sshd... /usr/sbin/sshd
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared
libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBNETCONF... yes
checking for library containing nc_init... none required
checking for library containing ncntf_dispatch_receive... none required
checking for library containing shm_open... -lrt
checking for pkg-config... /usr/bin/pkg-config
checking whether compiling and linking against OpenSSL works... yes
checking for library containing ovsrec_init... no
configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath

I looked for libopenvswitch.a and don't find it in the system.

On Mon, Mar 16, 2015 at 9:50 AM, Tomas Cejka notifications@github.com
wrote:

> Look at
> https://github.com/openvswitch/of-config/blob/master/INSTALL.md#open-vswitch-installation
> You have to configure and make Open vSwitch. That is the place where
> OF-CONFIG's configure looks for all OVS stuff...
> After successful build of OVS (make install is not necessary if you
> installed OVS in different way), configuration and build of OF-CONFIG can
> be done.
> https://github.com/openvswitch/of-config/blob/master/INSTALL.md#of-config-installation
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openvswitch/of-config/issues/2#issuecomment-81796724.

## 

abhijeet

**Comment by abhsob** [comment]
I was able to install and run ofc-server on RHEL 6.5 after following the
instructions on github. The only issue I had to resolve was in ovs-data.c.
I had to comment out
    {ADVERTISED_40000baseKR4_Full, "40Gb"},
    {ADVERTISED_40000baseCR4_Full, "40Gb"},
    {ADVERTISED_40000baseSR4_Full, "40Gb"},
    {ADVERTISED_40000baseLR4_Full, "40Gb"},

Looks like these are unsupported in RHEL6.5 env. If this is right then it
could be added to troubleshooting.

Thanks,
Abhijeet

On Mon, Mar 16, 2015 at 9:50 AM, Tomas Cejka notifications@github.com
wrote:

> Look at
> https://github.com/openvswitch/of-config/blob/master/INSTALL.md#open-vswitch-installation
> You have to configure and make Open vSwitch. That is the place where
> OF-CONFIG's configure looks for all OVS stuff...
> After successful build of OVS (make install is not necessary if you
> installed OVS in different way), configuration and build of OF-CONFIG can
> be done.
> https://github.com/openvswitch/of-config/blob/master/INSTALL.md#of-config-installation
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openvswitch/of-config/issues/2#issuecomment-81796724.

## 

abhijeet

**Comment by blp** [comment]
On Mon, Mar 16, 2015 at 03:06:44PM -0700, abhsob wrote:

> I was able to install and run ofc-server on RHEL 6.5 after following the
> instructions on github. The only issue I had to resolve was in ovs-data.c.
> I had to comment out
>     {ADVERTISED_40000baseKR4_Full, "40Gb"},
>     {ADVERTISED_40000baseCR4_Full, "40Gb"},
>     {ADVERTISED_40000baseSR4_Full, "40Gb"},
>     {ADVERTISED_40000baseLR4_Full, "40Gb"},
> 
> Looks like these are unsupported in RHEL6.5 env. If this is right then it
> could be added to troubleshooting.

Probably the correct solution would be to test for these constants and
define them if they are missing, e.g. as netdev-linux.c does for some
constants:

#ifndef ADVERTISED_Pause
#define ADVERTISED_Pause                (1 << 13)
#endif

**Comment by rkrejci** [comment]
Hi,
comments inline ...

Dne 16.3.2015 v 18:03 abhsob napsal(a):

> I already have openvswitch running:
> 
> ovs-vsctl show
> 760fdf5b-6eed-45b2-8573-5626dd978df1
> Bridge "br0"
> Controller "tcp:x.x.x.x:6633" (modified to hide network IP)
> Port "tap1"
> Interface "tap1"
> Port "br0"
> Interface "br0"
> type: internal
> Port "tap0"
> Interface "tap0"
> ovs_version: "2.3.1"
> 
> Just to clarify, I did not build openvswitch from github sources but used
> the tarball install. The
> ./configure --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

good, this is correct (and actually required)

> This is the output for
> [root@abso98 of-config]# ./configure
> --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
> checking for a BSD-compatible install... /usr/bin/install -c
> ...
> checking for library containing ovsrec_init... no
> configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath
> 
> I looked for libopenvswitch.a and don't find it in the system.

of-config search for it in the ovs-srcdir you set. Maybe it should have a better name or description, because it actually should be the "compiled source codes", not just the "source codes" I expect you have in /root/rpmbuild/SOURCES/openvswitch-2.3.1 - try to use /root/rpmbuild/BUILD/openvswitch-2.3.1instead.

Radek

**Comment by rkrejci** [comment]
hmm, I agree that we should test for these constants, but since we usethese constants when mapping rate from of-config data model from/to ioctl()'s ETHTOOL_GSET and ETHTOOL_SSET calls, we should probably ignore these values if they are not defined in system headers. Or do you think that the driver can define and use these rates on its own without support in the system headers, so we can get/set such values via ioctl()?

Radek

Dne 16.3.2015 v 23:13 Ben Pfaff napsal(a):

**Comment by blp** [comment]
On Tue, Mar 17, 2015 at 12:28:31AM -0700, Radek Krejčí wrote:

> hmm, I agree that we should test for these constants, but since we
> usethese constants when mapping rate from of-config data model from/to
> ioctl()'s ETHTOOL_GSET and ETHTOOL_SSET calls, we should probably
> ignore these values if they are not defined in system headers. Or do
> you think that the driver can define and use these rates on its own
> without support in the system headers, so we can get/set such values
> via ioctl()?

The machine on which the code builds is not necessarily the machine on
which the code runs.  The headers with which the code builds are not
necessarily the exact headers for the machine on which the code runs.
Given those facts, you're better off defining any constants that are
likely to be missing, so that the code can handle the features on any
machine where it might run, even though it might build on a machine
whose headers lack those features.

**Comment by abhsob** [comment]
Hi Radek,

I used the instructions in
http://git.openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob_plain;f=INSTALL.RHEL

using the distribution tarball. In that case, I don't see
the libopenvswitch.a anywhere on the system.

Then I deployed the openvswitch on another VM and did configure, make and
install as mentioned in the of-config install and then this file is found
in
./lib/libopenvswitch.a
./root/Downloads/openvswitch-2.3.1/lib/.libs/libopenvswitch.

Thanks,
Abhijeet

On Tue, Mar 17, 2015 at 12:17 AM, Radek Krejčí notifications@github.com
wrote:

> Hi,
> comments inline ...
> 
> Dne 16.3.2015 v 18:03 abhsob napsal(a):
> 
> > I already have openvswitch running:
> > 
> > ovs-vsctl show
> > 760fdf5b-6eed-45b2-8573-5626dd978df1
> > Bridge "br0"
> > Controller "tcp:x.x.x.x:6633" (modified to hide network IP)
> > Port "tap1"
> > Interface "tap1"
> > Port "br0"
> > Interface "br0"
> > type: internal
> > Port "tap0"
> > Interface "tap0"
> > ovs_version: "2.3.1"
> > 
> > Just to clarify, I did not build openvswitch from github sources but used
> > the tarball install. The
> > ./configure --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
> 
> good, this is correct (and actually required)
> 
> > This is the output for
> > [root@abso98 of-config]# ./configure
> > --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
> > checking for a BSD-compatible install... /usr/bin/install -c
> > ...
> > checking for library containing ovsrec_init... no
> > configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath
> > 
> > I looked for libopenvswitch.a and don't find it in the system.
> 
> of-config search for it in the ovs-srcdir you set. Maybe it should have a
> better name or description, because it actually should be the "compiled
> source codes", not just the "source codes" I expect you have in
> /root/rpmbuild/SOURCES/openvswitch-2.3.1 - try to use
> /root/rpmbuild/BUILD/openvswitch-2.3.1instead.
> 
> Radek
> 
> > On Mon, Mar 16, 2015 at 9:50 AM, Tomas Cejka notifications@github.com
> > wrote:
> > 
> > > Look at
> > > 
> > > https://github.com/openvswitch/of-config/blob/master/INSTALL.md#open-vswitch-installation
> > > You have to configure and make Open vSwitch. That is the place where
> > > OF-CONFIG's configure looks for all OVS stuff...
> > > After successful build of OVS (make install is not necessary if you
> > > installed OVS in different way), configuration and build of OF-CONFIG
> > > can
> > > be done.
> > > 
> > > https://github.com/openvswitch/of-config/blob/master/INSTALL.md#of-config-installation
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/openvswitch/of-config/issues/2#issuecomment-81796724>.
> > 
> > ## 
> > 
> > abhijeet
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/openvswitch/of-config/issues/2#issuecomment-81810604>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openvswitch/of-config/issues/2#issuecomment-82173299.

## 

abhijeet

**Comment by dcc6fvo** [comment]
same as @abhsob  on Ubuntu 16.10 and OVS 2.7 ..

_checking for library containing ovsrec_init... no
configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath_

$ sudo find / -iname libopenvswitch.a -type f 
/lib/libopenvswitch.a
/home/mininet/openvswitch-2.7.0/lib/.libs/libopenvswitch.a

any updates?

**Comment by Vivek788** [comment]
Even I am facing same problem with debian jessie and OVS 2.9.2. OF-config and OVS were taken from source.

**Comment by MaXiao93** [comment]
> Hi Radek,
> 
> I used the instructions in
> http://git.openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob_plain;f=INSTALL.RHEL
> 
> using the distribution tarball. In that case, I don't see
> the libopenvswitch.a anywhere on the system.
> 
> Then I deployed the openvswitch on another VM and did configure, make and
> install as mentioned in the of-config install and then this file is found
> in
> ./lib/libopenvswitch.a
> ./root/Downloads/openvswitch-2.3.1/lib/.libs/libopenvswitch.
> 
> Thanks,
> Abhijeet
> 
> On Tue, Mar 17, 2015 at 12:17 AM, Radek Krejčí [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > Hi,
> > comments inline ...
> > Dne 16.3.2015 v 18:03 abhsob napsal(a):
> > > I already have openvswitch running:
> > > ovs-vsctl show
> > > 760fdf5b-6eed-45b2-8573-5626dd978df1
> > > Bridge "br0"
> > > Controller "tcp:x.x.x.x:6633" (modified to hide network IP)
> > > Port "tap1"
> > > Interface "tap1"
> > > Port "br0"
> > > Interface "br0"
> > > type: internal
> > > Port "tap0"
> > > Interface "tap0"
> > > ovs_version: "2.3.1"
> > > Just to clarify, I did not build openvswitch from github sources but used
> > > the tarball install. The
> > > ./configure --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> > > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
> > 
> > 
> > good, this is correct (and actually required)
> > > This is the output for
> > > [root@abso98 of-config]# ./configure
> > > --with-ovs-srcdir=/root/rpmbuild/SOURCES/openvswitch-2.3.1
> > > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
> > > checking for a BSD-compatible install... /usr/bin/install -c
> > > ...
> > > checking for library containing ovsrec_init... no
> > > configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath
> > > I looked for libopenvswitch.a and don't find it in the system.
> > 
> > 
> > of-config search for it in the ovs-srcdir you set. Maybe it should have a
> > better name or description, because it actually should be the "compiled
> > source codes", not just the "source codes" I expect you have in
> > /root/rpmbuild/SOURCES/openvswitch-2.3.1 - try to use
> > /root/rpmbuild/BUILD/openvswitch-2.3.1instead.
> > Radek
> > > On Mon, Mar 16, 2015 at 9:50 AM, Tomas Cejka [notifications@github.com](mailto:notifications@github.com)
> > > wrote:
> > > > Look at
> > > > https://github.com/openvswitch/of-config/blob/master/INSTALL.md#open-vswitch-installation
> > > > You have to configure and make Open vSwitch. That is the place where
> > > > OF-CONFIG's configure looks for all OVS stuff...
> > > > After successful build of OVS (make install is not necessary if you
> > > > installed OVS in different way), configuration and build of OF-CONFIG
> > > > can
> > > > be done.
> > > > https://github.com/openvswitch/of-config/blob/master/INSTALL.md#of-config-installation
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > [https://github.com/openvswitch/of-config/issues/2#issuecomment-81796724>](https://github.com/openvswitch/of-config/issues/2#issuecomment-81796724%3E).
> > > 
> > > 
> > > 
> > > abhijeet
> > > —
> > > Reply to this email directly or view it on GitHub <
> > > [https://github.com/openvswitch/of-config/issues/2#issuecomment-81810604>](https://github.com/openvswitch/of-config/issues/2#issuecomment-81810604%3E).
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > [#2 (comment)](https://github.com/openvswitch/of-config/issues/2#issuecomment-82173299).
> 
> abhijeet
did you  have solve this problem? 
I have same issue: configure: error: libopenvswitch.a was not found. Try --with-ovs-libpath
Please help me , thanks！

**Comment by xroot88** [comment]
If you are still getting "error: possibly undefined macro: LT_INIT" you need to install libtool.
