### ISSUE TITLE
Question: datastore startup.xml file

### ISSUE THREAD

**Issue by JackLIN-F** [openvswitch/of-config#24]
Hi,
I have a question about datastore.
When copy running config to startup config, the startup.xml file has modified ??

Thanks,

**Comment by rkrejci** [comment]
The startup.xml is rewritten on server termination.

**Comment by JackLIN-F** [comment]
Hi rkrejci:

 I don't know what's mean? 
 When I change running-config and copy to start-config,  power of/on OVS switch. Does the start-config file any change?

Thanks,

**Comment by rkrejci** [comment]
By OVS switch, you mean the process or machine? OVS as process runs independently from ofc-server and startup.xml file here is in context of ofc-server. So, if you terminate and start OVS process, nothing happens with startup.xml, because ofc-server is still running. But stopping ofc-server should cause update of the startup.xml file.

**Comment by JackLIN-F** [comment]
Hi rkrejci:
You say: stopping ofc-server should cause update of the startup.xml file.

Could you tell me where is updated the startuo.xml file?  

file:ofconfig-datastore.c 
function: ofcds_copyconfig()
line: ??

Thanks

**Comment by rkrejci** [comment]
I don't understand your question.

1) location of startup.xml file is still the same - `OFC_DATADIR "/startup.xml"`
2) storing the startup data into startup.xml is done in `ofconfig-datastore.c:111`

**Comment by JackLIN-F** [comment]
Hi rkrejci:

Yes, The ofcds_free() function will trigger save startup.xml file.

How to trigger the function?
I cannot process the function.

```
ofc-server[7537]: Received message (session 18): <?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="3" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <copy-config>
    <target>
      <startup/>
    </target>
    <source>
      <running/>
    </source>
  </copy-config>
</rpc>
ofc-server[7537]: OFC COPY-CONFIG (from running to startup)
ofc-server[7537]: ofcds_getconfig,254,target=3
ofc-server[7537]: Adding new event (3)
ofc-server[7537]: Writing message (session 18): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <ok/>
</rpc-reply>
ofc-server[7537]: Received message (session 18): <?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="4" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <close-session/>
</rpc>
ofc-server[7537]: Writing message (session 18): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="4">
  <ok/>
</rpc-reply>
ofc-server[7537]: Freeing session for 'root'
ofc-server[7537]: Adding new event (6)
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
ofc-server[7537]: Created dummy session 0 for user 'root' (UID 0) - recovery session
```

**Comment by rkrejci** [comment]
Read again my comments in this thread - "stopping ofc-server should cause update of the startup.xml file".

**Comment by JackLIN-F** [comment]
Hi rkrejci:
I cannot see any change of the startup.xml file.
How to stopping ofc-server ?  Kill process thread?
One user connect to ofc-server and copy running to startup file. Does the startup.xml file any change?
or need to stop ofc-server should cause update of the startup.xml file? right?
Thanks

**Comment by JackLIN-F** [comment]
Hi rkrejci:
I think to modify the function ofcds_copyconfig(). When one user connect to ofc-server and copy running to startup file, the startup.xml file will updated 

ofcds_copyconfig()
......

```
    /* store the copy */
    if (target == NC_DATASTORE_STARTUP) {
        if (!rollbacking) {
            store_rollback(gds_startup, target);
        } else {
            xmlFreeDoc(gds_startup);
        }
        gds_startup = dst_doc;
```

add=>       if (gds_startup) {
add=>           xmlSaveFormatFile(OFC_DATADIR "/startup.xml", gds_startup, 1);
add=>       }

```
    } else {                /* NC_DATASTORE_CANDIDATE */
        if (!rollbacking) {
            store_rollback(gds_cand, target);
        } else {
            xmlFreeDoc(gds_cand);
        }
        gds_cand = dst_doc;
    }

    break;
```

**Comment by rkrejci** [comment]
No, the startup data can be also affected by edit-config or delete-config. Storing data to the persistent storage when the server is terminating should be enough. 

To stop the server, use signals - SIGTERM (15) or SIGINT (2), do not use SIGKILL (9).
