### ISSUE TITLE
Openflow entries

### ISSUE THREAD

**Issue by abhsob** [openvswitch/of-config#4]
Hi,

I was was looking at the OF-config spec as well as the openvswitch commands. I am not clear about whether this of-config implementation supports the ovs-ofctl commands especially those related to creation of flow entries like
 ovs-ofctl add-flow br0 priority=200,in_port=1,actions=output:2

I don't see an example of this in the netconf-tests. If there is any other user documentation/ examples that can help me with this let me know.

I understand this is not an issue. But I could not find any other forum for this.

Thanks,
Abhijeet

**Comment by cejkato2** [comment]
Hello Abhijeet,
usage of OpenFlow for configuration should be domain of OpenFlow controllers. OF-CONFIG is not meant to do such tasks... OF-CONFIG can be used to modify content of OVSDB such as add/delete port/queue/... like ovs-vsctl(8), ovsdb-client(1).
There is a document written for ONF that covers maping of OF-CONFIG to OVSDB but I'm not sure whether it is publicly accessible...
Tomas
