### ISSUE TITLE
Installation and Setup Issues

### ISSUE THREAD

**Issue by snrism** [openvswitch/of-config#7]
Hi,

I am trying to setup this installation in my Ubuntu machine, but I am facing some issues:
My setup:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
kernel version: 3.13.0-39-generic

Here are the steps that I followed:

OF-CONFIG Build Requirements

For the list of OF-CONFIG dependencies, I installed the following:
++ apt-get install autoconf automate gcc libtool python-libxml2 libxml2-dev m4 make openssl libssl-dev pkg-config

For OF-CONFIG dependencies, I installed:
++ apt-get install dbus-*dev

I then downloaded the below packages: 
++ openvswitch-2.3.1 and pyang-1.4.1

To stick to the INSTALL guide, I downloaded all packages in /root/ 

For Open vSwitch and libnetconf dependencies, I installed the following:
++ apt-get install libxslt-dev libssh2.1-dev libcurl4-openssl-dev xsltproc 

Open vSwitch Installation:

I did the untar and configuration as specified in INSTALL, but I wasn't sure if I need a symlink specification (ln -s /usr/src/kernels/2.6.32-504.8.1.el6.x86_64/ /lib/modules/2.6.32-504.el6.x86_64/build)

I started the ovs-ctl with system-id specification as:
++ /usr/local/share/openvswitch/scripts/ovs-ctl --system-id=random start

OF-CONFIG Installation
pyang: works fine, but 
libnetconf installation issues: The default libxml2 installation in ubuntu will not be picked up by lnctool, so I installed "apt-get python-libxml2"

OF-CONFIG configuration steps: After building, installation and configuration, I tried to start ofc-server which throws the following error:

ofc-server[26599]: D-Bus name error (Connection ":1.7" is not allowed to own the service "org.opennetworking.ofc.server" due to security policies in the configuration file)
ofc-server[26599]: Unable to became primary owner of the "org.opennetworking.ofc.server" bus.
ofc-server[26599]: Communication subsystem not initiated.

Kindly let me know what I am missing here.

**Comment by snrism** [comment]
@rananth Here is the current status when I tried to install in my Ubuntu 14.04 machine.

**Comment by rananth** [comment]
@rkrejci  Can you please take a look at this one and update the document as necessary?

**Comment by cejkato2** [comment]
@snrism Thank you very much for your report :-)
I expect the creation of symlink to kernel sources should not be neccessary because it is probably something strange in my used distro...

Have you tried to restart DBUS daemon?

Would you please provide us paths of DBUS configuration files in your distro?

@rkrejci Shouldn't we set UNiX socket by default for communication between agents and server?

**Comment by snrism** [comment]
@cejkato2: OK after restarting the dbus-daemon, I started the ofc-server and get the following output:
2015-04-02T07:43:56Z|00001|reconnect|INFO|unix://var/run/openvswitch/db.sock: connecting...
2015-04-02T07:43:56Z|00002|reconnect|INFO|unix://var/run/openvswitch/db.sock: connected
Could not load host key: /etc/ssh/ssh_host_ed25519_key
ofc-server[4974]: OpenFlow: ofc-bridge is not a bridge or a socket.
ofc-server[4974]: OpenFlow: could not connect to 'ofc-bridge' bridge. 

Does this mean, I create a bridge named `ofc-bridge` using ovs-vsctl? Some clarification on the order to start the daemons and after successfully starting them some explanation on basic usage will help a lot. 

Thanks,
Sriram

FYI: 
When I look for dbus-daemon, I get the following output:
/bin/dbus-daemon
/usr/lib/dbus-1.0/dbus-daemon-launch-helper
/usr/share/man/man1/dbus-daemon.1.gz

The dbus conf files are at:
/etc/init/dbus.conf
/usr/share/upstart/sessions/dbus.conf
/var/lib/dpkg/info/dbus.conffiles

**Comment by snrism** [comment]
@cejkato2 Quick update: 

I checked to see if `ofc-bridge` exists via ovs-vsctl show and see the following:
9a0e4317-1802-42a6-ac24-72197d09b92b
    Bridge ofc-bridge
        fail_mode: secure
        Port ofc-bridge
            Interface ofc-bridge
                type: internal

Then, I tried to restart ofc-server and get the following output:
2015-04-02T07:54:44Z|00001|reconnect|INFO|unix://var/run/openvswitch/db.sock: connecting...
2015-04-02T07:54:44Z|00002|reconnect|INFO|unix://var/run/openvswitch/db.sock: connected
Could not load host key: /etc/ssh/ssh_host_ed25519_key
ofc-server[5271]: OpenFlow: ofc-bridge: failed to connect to socket (Connection reset by peer).
ofc-server[5271]: OpenFlow: could not connect to 'ofc-bridge' bridge.

Maybe I am missing something here or not starting the required daemons propoerly. Any help is appreciated.

Thanks,
Sriram

**Comment by budnyjj** [comment]
I also have installed of-config daemon on Ubuntu 14.04.
Your installation looks seems to be correct, except these messages:

```
ofc-server[5271]: OpenFlow: ofc-bridge: failed to connect to socket (Connection reset by peer).
ofc-server[5271]: OpenFlow: could not connect to 'ofc-bridge' bridge.
```

You can correct them by adding 'ofc-bridge' bridge, and start ofc-server after it:

``` bash
sudo ip link add ofc-bridge type veth peer name ofc-bridge-peer
sudo ip link set ofc-bridge up
sudo ofc-server -f
```

I think, that it is useful to place this hint into project documentation.

**Comment by snrism** [comment]
I am still facing some issues.
ofc-server[18449]: Unable to became primary owner of the "org.opennetworking.ofc.server" bus.
ofc-server[18449]: Communication subsystem not initiated.

Will reconfirm if I am setting up correctly. 

Also, are there any starter guides once we have the setup working?

Thanks,
Sriram

**Comment by rkrejci** [comment]
What user is running ofc-server? is it the same user as in case of openvswitch?

D-Bus is used for communication between the ofc-server and ofc-agents. It allows more detailed security settings for intercommunication, so this way you can limit users available to connect to the ofc-server. By default, D-Bus is set to allow only root running the ofc-server and any user can connect to it via ofc-agent (OF-CONFIG connection to the SSH server). Changes can be made in the /etc/dbus-1/system.d/org.opennetworking.ofc.conf file.

There is more simple alternative communication to D-Bus - UNIX sockets. When you compile the project with the configure's --disable-dbus option, the sockets will be used for communication. In such a case, there is no control on access rights and anyone can connect to ofc-server. The access control can be added in future, but currently this limitation is for simplicity.

In both cases, the ofc-server should run with the same user privileges as openvswitch to allow interaction. I'm going to add this note into the INSTALL document.

**Comment by snrism** [comment]
@rkrejci Thanks, I disabled the dbus, restarted the dbus-daemon that was running and started the ofc-server and it works. Now, time for some experimental setup. I plan to use the test files you have in the netconf-tests folder to see if I can issue basic commands via ofc-server...will keep you posted.

**Comment by MaXiao93** [comment]
@snrism I get the same issue:
2018-11-26T02:02:02Z|00002|reconnect|INFO|unix://var/run/openvswitch/db.sock: connected
ofc-server[2977]: OpenFlow: ofc-bridge is not a bridge or a socket.
ofc-server[2977]: OpenFlow: could not connect to 'ofc-bridge' bridge.
May I ask if you have solved this problem? Thanks!
