### ISSUE TITLE
Write separate installation guide for different distros

### ISSUE THREAD

**Issue by snrism** [openvswitch/of-config#8]
Hi,

Similar to OVS installation, we might require Installation guide for different distros (if you believe there are unique differences for each distro)

Kindly check OVS https://github.com/openvswitch/ovs

I am happy to open a Pull Request once I get this installation successful in my distro.

@rananth Let me know.

Thanks,
Sriram

**Comment by rananth** [comment]
Agreed if this makes pulling dependencies and paves way for smoother installation, we should consider that. This is something that can be discussed in the mailing list/regular call.  @rkrejci : Any comments?

**Comment by cejkato2** [comment]
I thought  about it and the only thing that is related to of-config installation and could be distro-dependent is probably DBUS... I think that the rest is independent or it is related to Open vSwitch. Do you agree?

**Comment by snrism** [comment]
@cejkato2 OK. If that is the case, maybe we can update the README to clarify that in few sentences. I suggest updating the README for better clarity

Requirements (basically restructure current text):
++ Required
++ Optional
++ Additional info on specific distro (if any like d-bus)

Installation:
++ OVS 
++ OF-Config (pyang, libnetconf)

Configuration
Build
Startup
Troubleshooting

In our call this week, Anantha and Deepak requested me to open some of my suggestions as new issues. I will add them for your consideration and happy to take that task if you are OK with it.

Thanks
Sriram
